### ISSUE TITLE
[FR] Implement the networking piece (network-mux) as a separate Cargo library

### ISSUE THREAD

**Issue by mark-stopka** [AndrewWestberg/cncli#2]
Hi,
I have interest in testing Ouroboros consensus in a variety of different networking conditions, and this tool partially implementing `network-mux` module used in `cardano-node` would come supper handy (e.q. we could create a relay that on one side talks to `cardano-node` and on other side uses PolderCast from `jormungandr`), would it be possible to move networking piece into a library, and perhaps @nicolasDP could write a `rust-cardano-relay` combining both PolderCast and `cardano-node network-mux`...

**Comment by mark-stopka** [comment]
@pavlix, can you perhaps have a look?

**Comment by pavlix** [comment]
I will have a look into this in the next two weeks.

**Comment by AndrewWestberg** [comment]
I'm still a bit of a rust noob and this is my very first project. I'm not sure how to break things out into a separate crate.

**Comment by mark-stopka** [comment]
> I'm still a bit of a rust noob and this is my very first project. I'm not sure how to break things out into a separate crate.

Don't worry about that, that is why I called my boy @pavlix on it, he is a bit busy with some other tasks I've given him right now, but he will get on it... :-)

**Comment by mark-stopka** [comment]
Work is getting started, @AndrewWestberg, is there any particular order in which you would like the mini-protocols to be implemented? We will obviously implementy those used by `cncli` first, but we would like you to start using them as soon as possible so we have intergation testing taken care of...

Repository: [2nd-Layer/rust-cardano-ouroboros-network](https://github.com/2nd-Layer/rust-cardano-ouroboros-network/)
  - Project: [Implement set of mini-protocols required for cncli](https://github.com/2nd-Layer/rust-cardano-ouroboros-network/projects/1)
  - Milestone: [Implement mini-protocols required to replace embeded versions in cncli](https://github.com/2nd-Layer/rust-cardano-ouroboros-network/milestone/1)

**Comment by AndrewWestberg** [comment]
The protocols need to be implemented in the following order.
1.) handshake - This protocol needs to complete fully before any other protocols are allowed.
2.) transaction protocol - I implemented a stubbed version of this just so I could tell the remote node I wouldn't have any transactions to send it. The reason this is #2 is because the server has agency at the start of the connection and will be sending you a message that needs to be handled. I would recommend doing the same stubbed implementation until you are ready to handle transaction sending.
3.) chainsync - sync the block headers from the remote.
4.) blocksync - sync the blocks for the headers you've received.

All of these are implemented in cncli except #4.

**Comment by mark-stopka** [comment]
@AndrewWestberg thanks, I will raise individual tickets for each mini protocol and make sure that @pavlix implements them in the desired order.

**Comment by mark-stopka** [comment]
@AndrewWestberg I suppose by BlockSync you mean BlockFetch as described in section 2.6 of the specification?

![image](https://user-images.githubusercontent.com/18139116/100581295-cc382d80-32e7-11eb-875b-cc9ecc3f4310.png)

**Comment by AndrewWestberg** [comment]
Yes. BlockFetch is what I meant.

**Comment by AndrewWestberg** [comment]
Closing as we're relying on the external crate as of 0.4.0.
